### ISSUE TITLE
Why is the symbol not found?

### ISSUE THREAD

**Issue by chinoll** [rustsbi/rustsbi#13]
= note: rust-lld: error: /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/libriscv-d89f58cca82b1706.rlib(riscv.o): cannot link object files with different floating-point ABI
          rust-lld: error: undefined symbol: _max_hart_id
          >>> referenced by main.rs:76 (platform/k210/src/main.rs:76)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          >>> referenced by main.rs:76 (platform/k210/src/main.rs:76)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          
          rust-lld: error: undefined symbol: _stack_start
          >>> referenced by main.rs:76 (platform/k210/src/main.rs:76)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          
          rust-lld: error: undefined symbol: _hart_stack_size
          >>> referenced by main.rs:76 (platform/k210/src/main.rs:76)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          >>> referenced by main.rs:76 (platform/k210/src/main.rs:76)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          
          rust-lld: error: undefined symbol: _sbss
          >>> referenced by main.rs:118 (platform/k210/src/main.rs:118)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          
          rust-lld: error: undefined symbol: _ebss
          >>> referenced by main.rs:118 (platform/k210/src/main.rs:118)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          
          rust-lld: error: undefined symbol: _sdata
          >>> referenced by main.rs:119 (platform/k210/src/main.rs:119)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)
          
          rust-lld: error: undefined symbol: _sidata
          >>> referenced by main.rs:119 (platform/k210/src/main.rs:119)
          >>>               /root/rustsbi/target/riscv64gc-unknown-none-elf/debug/deps/rustsbi_k210-fa3b824066eafffd.1hd3n18pcrelb196.rcgu.o:(_start)

为什么会找不到这些符号
target = riscv64gc-unknown-none-elf

**Comment by luojia65** [comment]
用target = riscv64imac-unknown-none-elf。这些符号是链接器脚本得到的，链接器脚本在.cargo/config.toml里给出，我只给riscv32imac、riscv64imac写了对应的链接器脚本，没有给gc写。原理上给gc写也是可以的，不过我们的sbi设计里尽量避免使用浮点数指令，这样可以少保存一些上下文，所以通常为imac指令集编写就够了。
