### ISSUE TITLE
Page fault delegation

### ISSUE THREAD

**Issue by Yinwhe** [rustsbi/rustsbi#15]
话说根据boot之后sbi输出的medeleg来看，是不是Page fault没有进行委托QAQ

**Comment by luojia65** [comment]
哪个平台？

**Comment by TLBZero** [comment]
[rustsbi] Platform: K210 (Version 0.2.0)
[rustsbi] misa: RV64ACDFIMSU
[rustsbi] mideleg: 0x22
[rustsbi] medeleg: 0x1ab
这里的medeleg里应该是没有代理page fault的吧

**Comment by luojia65** [comment]
我记得K210上好像没有单独的缺页异常，当时的版本被合并到访存异常里面了

**Comment by TLBZero** [comment]
嗷嗷这样，那我后面在试试叭，谢谢luojia！

**Comment by luojia65** [comment]
好，后面有问题再打开这个issue
