### ISSUE TITLE
RustSBI的浮点指令支持

### ISSUE THREAD

**Issue by sunshine-lcc** [rustsbi/rustsbi#19]
我在用fmv.w.x指令时，发现被RustSBI视为非法指令
请问RustSBI没有提供浮点指令的支持吗？

**Comment by luojia65** [comment]
没有！

**Comment by luojia65** [comment]
edited on 2022/5/16: 在M态需要打开mstatus.FS就可以使用了，需要到各个平台中具体实现才可以，这部分并非由RustSBI本身控制
