### ISSUE TITLE
能否像opensbi一样绑定kernel吗

### ISSUE THREAD

**Issue by chen-coco** [rustsbi/rustsbi#24]
或使用其他的方式实现

**Comment by luojia65** [comment]
此话怎讲？如果我理解为跳转到内核的话，这是由rustsbi的实现实现的，比如具体的引导程序会做这部分的代码。

**Comment by chen-coco** [comment]
在opensbi编译的时候能将内核一起打包到fw_playload.bin这一个文件当中，就像这样的功能。
方便spike模拟

**Comment by luojia65** [comment]
考虑用objcopy来实现这个功能？我觉得可以试着在内核的编译脚本里做。RustSBI设计的目标之一是一个库，它作为Rust生态圈的一部分，被其它引导程序依赖，构成完整的引导程序，可能打包程序略微超过了RustSBI项目本身的目标，可以去项目的各个实现中找找看。

**Comment by chen-coco** [comment]
好的，谢谢 :)
