### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by YdrMaster** [rustsbi/rustsbi#34]

**Comment by luojia65** [comment]
我设想里的0.3.0计划：
- legacy接口放进features（已完成）
- 上游的包（sbi-spec等）设计稳定
- 虚拟化软件使用rustsbi，也就是放一个feature把init_*关掉，以实例形式给出接口抽象（init_*是单例）
后面再探索和其它接口的并存问题（蓬莱环境啊这些）。还有什么要补充的吗？

**Comment by YdrMaster** [comment]
> 我设想里的0.3.0计划：
> 
> * legacy接口放进features（已完成）
> * 上游的包（sbi-spec等）设计稳定
> * 虚拟化软件使用rustsbi，也就是放一个feature把init_*关掉，以实例形式给出接口抽象（init_*是单例）
> 
> 后面再探索和其它接口的并存问题（蓬莱环境啊这些）。还有什么要补充的吗？

虚拟化软件使用，我看见之前留的模块了，不过现在有下游设计吗？感觉第一次实现这俩得同步做

**Comment by luojia65** [comment]
下游现在还是一些爱好者项目，还没有看到产业或者研究上支持的，我们未来慢慢发现。@YdrMaster

**Comment by YdrMaster** [comment]
我主要是担心没有下游设计的话库接口做了无法验证。不过还有另一种思路，就是不做 feature，直接把现在的多个单例合并成一个类型的单例，这样可以用现有的普通 sbi 实现来验证。

**Comment by luojia65** [comment]
Released at https://github.com/rustsbi/rustsbi/releases/tag/v0.3.0
