### ISSUE TITLE
Update README, CHANGELOG for next publishing

### ISSUE THREAD

**Issue by YdrMaster** [rustsbi/rustsbi#63]

**Comment by luojia65** [comment]
Documentation for missing 12 to 16 chapters has been added to readme on this commit: https://github.com/rustsbi/sbi-rt/commit/4a90a5f638b156b5f9d83abc12cd67d1498390b7 . We added `sbi_pmu_counter_fw_read_hi`, but we missed `sbi_pmu_snapshot_set_shmem`; will be added soon.

Reference:
![图片](https://github.com/user-attachments/assets/c64cd7b7-3bf2-4b58-ae97-0d28290be53d)

**Comment by luojia65** [comment]
Added in: https://github.com/rustsbi/rustsbi/pull/77
