### ISSUE TITLE
How to work on riscv32?

### ISSUE THREAD

**Issue by chaoyangnz** [rustsbi/rustsbi#9]
I am using `qemu-system-riscv32` to load rustsbi, and nothing to show.

If possible, please help provide documentation about how to build for riscv32.

**Comment by luojia65** [comment]
Thank you for raising issue! The reference implementation for QEMU does not support RISC-V RV32 yet. I'll do it recently, as RV32's QEMU have different configuration than RV64's. 
By now, you can try RustSBI on QEMU for riscv64 yet.

**Comment by luojia65** [comment]
We have devided NOT to support qemu32 in reference implementation due to adds of complexity. If you really want it, start a pull request or work on your own repository.

**Comment by chaoyangnz** [comment]
thanks
